trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  repositoryName: 'StefanL02'

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  # Install dependencies
  - script: |
      npm ci
    displayName: 'Install Dependencies'

  # Run Jest tests
  - script: |
      echo "Running Jest Tests..."
      npx jest --ci --reporters=jest-junit
    displayName: 'Run Jest Tests'

  # Publish Jest test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/jest-junit.xml'
      testRunTitle: 'Jest Test Results'
      mergeTestResults: true

  # Build Docker container and push to registry (optional)
  - task: Docker@2
    inputs:
      containerRegistry: '<docker connection>'  # Replace with your registry
      repository: $(repositoryName)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

  # Post-test message
  - script: |
      echo "Pipeline completed successfully!"
    displayName: 'Post-Pipeline Notification'
