trigger:
- main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu as the build agent

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Use Node.js version 18.x
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Run Jest tests
- script: |
    npm test -- --ci --reporters=jest-junit
  displayName: 'Run Jest Tests'

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/junit.xml'
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'

# Verify coverage report
- script: |
    echo "Validating coverage report"
    ls $(System.DefaultWorkingDirectory)/coverage
  displayName: 'Verify Coverage Report'
