trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Specify the Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install mocha-junit-reporter --save-dev
     npm install -g mocha
    npm install mocha-junit-reporter --save-dev
  displayName: 'Install dependencies'

- script: |
    # Ensure the TestResults directory exists
    mkdir -p TestResults
    # Run tests and generate the XML file with mocha-junit-reporter
    mocha --reporter mocha-junit-reporter --reporter-options mochaFile=TestResults/Test1.xml seleniumTest.js
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TestResults/Test1.xml'  # Path to the generated XML file
    testRunTitle: 'Connect Four Game Tests'
  displayName: 'Publish Test Results'
