trigger:
- main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu as the build agent

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Use Node.js version 18.x
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Ensure Jest has executable permissions
- script: |
    chmod +x ./node_modules/.bin/jest
  displayName: 'Set Jest Executable Permissions'

# Run Jest tests
- script: |
    npx jest --ci --reporters=jest-junit || echo "Tests failed, continuing pipeline"
  displayName: 'Run Jest Tests'
  continueOnError: true  # Allow the pipeline to continue even if tests fail

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/junit.xml'
    failTaskOnFailedTests: false  # Do not fail the pipeline on failed tests
  displayName: 'Publish Test Results'
  condition: succeededOrFailed()  # Publish results even if tests failed