trigger:
  branches:
    include:
      - main  # Triggers the pipeline on commits to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Uses the latest Ubuntu image for the pipeline (can be changed if needed)

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Specify the Node.js version
  displayName: 'Install Node.js'

# Step 2: Install dependencies and debug
- script: |
    # Install all dependencies including selenium-webdriver, chromedriver, mocha, and mocha-junit-reporter
    npm install
    # List installed packages to ensure everything is installed
    npm list --depth=2
    # List files in the current directory for verification
    ls -l
  displayName: 'Install dependencies and debug'

# Step 3: Run Selenium tests using Mocha with verbose output
- script: |
    # Use Node.js to ensure the TestResults directory exists in a cross-platform way
    node -e "require('fs').mkdirSync('TestResults', { recursive: true });"
    
    # List the files in the working directory to ensure the test file is present
    ls -l
    
    # Run Mocha tests using selenium-webdriver and output results to TestResults folder
    npx mocha --reporter spec mocha-junit-reporter --reporter-options mochaFile=TestResults/Test1.xml seleniumTest.js
  displayName: 'Run Selenium Tests'

# Step 4: Publish test results to Azure DevOps
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TestResults/Test1.xml'  # Path to the generated XML file
    testRunTitle: 'Selenium Tests'
  displayName: 'Publish Test Results'
