# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  # Adjust this to your primary branch if different

pool:
  vmImage: 'ubuntu-latest'  # The environment to run the build

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Specify the Node.js version required
  displayName: 'Install Node.js'

# Step 2: Install Dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Step 3: Run Tests
- script: |
    echo "hello world"
  displayName: 'Run Tests'
