trigger: 
  branches:
    include:
      - main  # Trigger on pushes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for pipeline execution

variables:
  repositoryName: '<target repository name>'  # Replace with the actual repository name

steps:
  # Step 1: Build and Push Docker Image
  - task: Docker@2
    inputs:
      containerRegistry: '<docker connection>'  # Replace with your Docker registry service connection
      repository: $(repositoryName)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
    displayName: 'Build and Push Docker Image'

  # Step 2: Set Node.js Version
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'  # Specify the Node.js version
    displa
