trigger:
  branches:
    include:
      - main  # Triggers the pipeline on commits to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux agent; change if needed

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Specify the Node.js version to use
  displayName: 'Install Node.js'

# Step 2: Install Dependencies
- script: |
    echo "Installing dependencies..."
    npm ci  # Clean install dependencies from package-lock.json
  displayName: 'Install Dependencies'

# Step 3: Create Coverage Directory
- script: |
    echo "Creating Coverage directory..."
    mkdir -p coverage
  displayName: 'Create Coverage Directory'

# Step 4: Run Node.js Tests with Clover XML Reporting
- script: |
    echo "Running Node.js tests..."
    if [ ! -f "tests/testsnodeTest.test.js" ]; then 
      echo "Test file not found!"; 
      exit 1; 
    fi
    npx mocha tests/testsnodeTest.test.js --reporter mocha-lcov-reporter > coverage/clover.xml
  displayName: 'Run Node.js Tests and Generate Clover XML Report'

# Step 5: Publish Clover XML Code Coverage Results
- script: |
    echo "Publishing Clover XML Code Coverage Report..."
    if [ ! -f "coverage/clover.xml" ]; then 
      echo "Clover XML file not found!"; 
      exit 1; 
    fi
  displayName: 'Publish Clover XML Code Coverage Report'
