trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'


steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  # Install dependencies
  - script: |
      npm install
    displayName: 'Install Dependencies'

  # Run Jest tests
  - script: |
      echo "Running Jest Tests..."
      npm jest --ci --reporters=jest-junit
    displayName: 'Run Jest Tests'

  # Publish Jest test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/jest-junit.xml'
      testRunTitle: 'Jest Test Results'
      mergeTestResults: true

  # Post-test message
  - script: |
      echo "Pipeline completed successfully!"
    displayName: 'Post-Pipeline Notification'
